// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/_404.tsx";
import * as $1 from "./routes/_app.tsx";
import * as $2 from "./routes/index.tsx";
import * as $$0 from "./islands/filters.jsx";
import * as $$1 from "./islands/footer.jsx";
import * as $$2 from "./islands/form-and-results.jsx";
import * as $$3 from "./islands/main-form.jsx";

const manifest = {
  routes: {
    "./routes/_404.tsx": $0,
    "./routes/_app.tsx": $1,
    "./routes/index.tsx": $2,
  },
  islands: {
    "./islands/filters.jsx": $$0,
    "./islands/footer.jsx": $$1,
    "./islands/form-and-results.jsx": $$2,
    "./islands/main-form.jsx": $$3,
  },
  baseUrl: import.meta.url,
};

export default manifest;
